honoka.webflux.security:
  white-list:
    - /auth/login
    - /auth/logout
    - /auth/oauth2/**
    - /auth/.well-known/**
    - /user/user/register
  authorities:
    - permission: permission1:a1:a
      paths:
        - /service1/hello2
    - role: user2
      paths:
        - /service1/hello3
