GET {{url_prefix.auth}}/.well-known/oauth-authorization-server

###
GET {{url_prefix.auth}}/oauth2/jwks

###
GET {{url_prefix.gateway}}/auth/.well-known/oauth-authorization-server

###
GET {{url_prefix.gateway}}/auth/auth/web/routeAuthorities
Authorization: {{token_type}} {{access_token}}
