spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root123
  flyway:
    enabled: true
    locations: classpath:flyway/sql
    baseline-on-migrate: true
    baseline-version: 0.0.0
    validate-on-migrate: false
    clean-disabled: true
    clean-on-validation-error: false
  data:
    redis:
      host: vm.honoka.de
      port: 6379
      username: redis
      password: redis123

honoka:
  starter:
    mybatis:
      enabled: true

mybatis-plus:
  # classpath*:mapper/**/*.xml为默认值，默认扫描resources/mapper目录及其子目录下所有xml文件
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

app:
  datasource:
    url:
      prefix: jdbc:mysql://vm.honoka.de:3306/
      suffix: ?serverTimezone=GMT%2B8
