spring:
  datasource:
    url: ${microservice-demo.datasource.url.prefix}microservice_demo_auth${microservice-demo.datasource.url.suffix}

microservice-demo:
  auth:
    key-id: 3072c7b9-1302-370e-82cb-eb0bbf859f62
    key-path: ./files/auth-key/auth-key.pem
