spring:
  datasource:
    url: ${microservice-demo.datasource.url.prefix}microservice_demo_user${microservice-demo.datasource.url.suffix}

logging:
  level:
    de.honoka.demo.microservice.user.mapper: debug
