spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://vm.honoka.de:3306/microservice_demo_service1?serverTimezone=GMT%2B8
    username: root
    password: root123
